-- 
CREATE TABLE TB_ADMIN
(	
	ADMIN_ID INTEGER NOT NULL AUTO_INCREMENT COMMENT '管理员ID' ,

	ADMIN_ROLE INTEGER COMMENT '角色' ,
	ADMIN_NAME VARCHAR(128) NOT NULL COMMENT '姓名' ,
	ADMIN_PWD VARCHAR(64) COMMENT '密码' ,
	ENABLE INTEGER DEFAULT '1' COMMENT '启用' ,
	CHECK_STATE INTEGER DEFAULT '0' NOT NULL COMMENT '审核状态' ,
	ADMIN_IDNO VARCHAR(32) COMMENT '唯一标识' ,
	ADMIN_NATION VARCHAR(32) COMMENT '国家' ,
	ADMIN_PROVINCE VARCHAR(32) COMMENT '省' ,
	ADMIN_CITY VARCHAR(32) COMMENT '城市' ,
	ADMIN_ADDRESS VARCHAR(128) COMMENT '地址' ,
	ADMIN_ORG VARCHAR(128) COMMENT '组织' ,
	ADMIN_UNIT VARCHAR(128) COMMENT '机构' ,
	ADMIN_PHONE VARCHAR(32) COMMENT '电话' ,
	ADMIN_EMAIL VARCHAR(32) COMMENT '邮箱' ,
	CERT_CN VARCHAR(128) COMMENT '证书CN' ,
	CERT_SN VARCHAR(64) COMMENT '证书SN' ,
	CERT_SIGN_DATE TIMESTAMP COMMENT '证书签发时间' ,
	CERT_NOT_BEFORE TIMESTAMP COMMENT '证书起始日期' ,
	CERT_NOT_AFTER TIMESTAMP COMMENT '证书过期日期' ,
	CERT_SUBJECT_DN VARCHAR(256) COMMENT '证书主题' ,
	CERT_EXTENSION VARCHAR(256) COMMENT '证书扩展' ,
	CERT_POLICY_NAME VARCHAR(32) COMMENT '证书策略' ,
	CERT_ISSURE_DN VARCHAR(256) COMMENT '证书发放者DN' ,
	CERT_SIGNATURE BLOB COMMENT '签名证书' ,
	CERT_ENCRYPTION BLOB COMMENT '加密证书' ,


    PRIMARY KEY (ADMIN_ID)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COLLATE = gbk_chinese_ci;

-- 
CREATE TABLE TB_APP
(	
	APP_ID INTEGER NOT NULL AUTO_INCREMENT ,

	APP_NAME VARCHAR(128) NOT NULL ,
	APP_URL VARCHAR(1024) NOT NULL ,
	APP_DESC VARCHAR(1024) ,
	CHECK_STATE INTEGER DEFAULT '0' NOT NULL ,


    PRIMARY KEY (APP_ID)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COLLATE = gbk_chinese_ci;

-- 
CREATE TABLE TB_APP_ROLE
(	
	APPROLE_ID INTEGER NOT NULL AUTO_INCREMENT ,

	APP_ID INTEGER NOT NULL ,
	APPROLE_NAME VARCHAR(128) NOT NULL ,
	APPROLE_VALUE VARCHAR(1024) NOT NULL ,
	APPROLE_DESC VARCHAR(1024) NOT NULL ,
	CHECK_STATE INTEGER DEFAULT '0' NOT NULL ,


    PRIMARY KEY (APPROLE_ID)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COLLATE = gbk_chinese_ci;

-- 
CREATE TABLE TB_CHECK
(	
	CHECK_ID INTEGER NOT NULL AUTO_INCREMENT ,

	ADMIN_ID INTEGER NOT NULL ,
	ACT_TIME TIMESTAMP DEFAULT 'now()' NOT NULL ,
	ACT_NAME VARCHAR(128) ,
	ACT_CLASS BLOB ,
	ACT_DESC BLOB ,
	CHECK_ADMIN_ID INTEGER ,
	CHECK_TIME TIMESTAMP ,
	CHECK_RES_ID INTEGER DEFAULT '-1' ,
	CHECK_DESC VARCHAR(2048) ,


    PRIMARY KEY (CHECK_ID)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COLLATE = gbk_chinese_ci;

-- 
CREATE TABLE TB_DEPT
(	
	DEPT_ID INTEGER NOT NULL AUTO_INCREMENT ,

	DEPT_NAME VARCHAR(128) ,
	DEPT_DESC VARCHAR(512) ,
	PARENT_ID INTEGER ,
	IS_LEAF INTEGER ,
	CHECK_STATE INTEGER DEFAULT '0' ,


    PRIMARY KEY (DEPT_ID)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COLLATE = gbk_chinese_ci;

-- 
CREATE TABLE TB_LOG
(	
	LOG_ID INTEGER NOT NULL AUTO_INCREMENT ,

	LOG_WHO INTEGER ,
	LOG_WHEN TIMESTAMP ,
	LOG_DO VARCHAR(128) ,
	LOG_WHAT VARCHAR(2048) ,
	LOG_RES_ID INTEGER ,


    PRIMARY KEY (LOG_ID)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COLLATE = gbk_chinese_ci;

-- 
CREATE TABLE TB_LOG_RES
(	
	LOG_RES_ID INTEGER ,
	LOG_RES VARCHAR(4) 

)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COLLATE = gbk_chinese_ci;

-- 
CREATE TABLE TB_ORG
(	
	ORG_ID INTEGER NOT NULL COMMENT '编号' ,

	ORG_NAME VARCHAR(128) COMMENT '机构名称' ,
	ORG_FULL_NAME VARCHAR(256) COMMENT '机构名称' ,
	ORG_NAME_PINYIN VARCHAR(256) COMMENT '机构名称拼音' ,
	ORG_STATUS INTEGER COMMENT '机构状态' ,
	ORG_INDATE TIMESTAMP COMMENT '创建时间' ,
	ORG_UPDATE TIMESTAMP COMMENT '修改时间' ,
	ORG_CODE VARCHAR(32) COMMENT '机构编码' ,
	ORG_PARENT_ID INTEGER COMMENT '上级机构' ,
	ORG_PARENT_CODE VARCHAR(64) COMMENT '上级机构' ,
	ORG_TYPE INTEGER COMMENT '机构类型' ,
	ORG_FULL_CODE VARCHAR(1024) COMMENT '机构完整编码' ,
	ORDER_INDEX VARCHAR(32) COMMENT '机构排序码' ,
	ORDER_FULL_INDEX VARCHAR(1024) COMMENT '机构排序完整编码' ,
	ORG_LEVEL INTEGER COMMENT '机构级别' ,
	ORG_LINKMAN VARCHAR(32) COMMENT '联系人' ,
	ORG_TELEPHONE VARCHAR(20) COMMENT '联系电话' ,
	ORG_POSTCODE VARCHAR(20) COMMENT '邮政编码' ,
	ORG_ADDRESS VARCHAR(128) COMMENT '联系地址' ,
	ORG_DES VARCHAR(512) COMMENT '机构描述' ,
	ADMIN_ID INTEGER COMMENT '操作管理员' ,


    PRIMARY KEY (ORG_ID)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COLLATE = gbk_chinese_ci;

-- 
CREATE TABLE TB_USER
(	
	USER_ID INTEGER NOT NULL AUTO_INCREMENT COMMENT '用户ID' ,

	DEPT_ID INTEGER COMMENT 'DEPT_ID' ,
	USER_CN VARCHAR(32) COMMENT '用户编号' ,
	USER_NAME VARCHAR(32) COMMENT '姓名' ,
	USER_NAMEPY VARCHAR(32) COMMENT '姓名拼音' ,
	USER_ORG VARCHAR(64) COMMENT '组织' ,
	USER_UNIT VARCHAR(64) COMMENT '单位' ,
	USER_OFFICE VARCHAR(128) COMMENT '处室' ,
	USER_EMAIL VARCHAR(32) COMMENT '电子邮件' ,
	USER_ADDR VARCHAR(256) COMMENT '联系地址' ,
	USER_PHONE VARCHAR(32) COMMENT '联系电话' ,
	REG_TIME TIMESTAMP COMMENT '注册时间' ,
	USER_RESERVE1 VARCHAR(4096) COMMENT '保留1' ,
	USER_RESERVE2 VARCHAR(4096) COMMENT '保留2' ,
	USER_RESERVE3 VARCHAR(4096) COMMENT '保留3' ,
	USER_RESERVE4 VARCHAR(4096) COMMENT '保留4' ,
	CHECK_STATE INTEGER ,


    PRIMARY KEY (USER_ID)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COLLATE = gbk_chinese_ci;

-- 
CREATE TABLE TB_USER_RIGHTS
(	
	USER_ID INTEGER NOT NULL ,
	APP_ID INTEGER NOT NULL ,
	APPROLE_ID INTEGER 

)
ENGINE = InnoDB
DEFAULT CHARACTER SET = gbk
COLLATE = gbk_chinese_ci;

