-- 
CREATE TABLE TB_ADMIN
(	
	ADMIN_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,

	ADMIN_ROLE INTEGER ,
	ADMIN_NAME VARCHAR(128) NOT NULL ,
	ADMIN_PWD VARCHAR(64) ,
	ENABLE INTEGER DEFAULT '1' ,
	CHECK_STATE INTEGER DEFAULT '0' NOT NULL ,
	ADMIN_IDNO VARCHAR(32) ,
	ADMIN_NATION VARCHAR(32) ,
	ADMIN_PROVINCE VARCHAR(32) ,
	ADMIN_CITY VARCHAR(32) ,
	ADMIN_ADDRESS VARCHAR(128) ,
	ADMIN_ORG VARCHAR(128) ,
	ADMIN_UNIT VARCHAR(128) ,
	ADMIN_PHONE VARCHAR(32) ,
	ADMIN_EMAIL VARCHAR(32) ,
	CERT_CN VARCHAR(128) ,
	CERT_SN VARCHAR(64) ,
	CERT_SIGN_DATE TIMESTAMP ,
	CERT_NOT_BEFORE TIMESTAMP ,
	CERT_NOT_AFTER TIMESTAMP ,
	CERT_SUBJECT_DN VARCHAR(256) ,
	CERT_EXTENSION VARCHAR(256) ,
	CERT_POLICY_NAME VARCHAR(32) ,
	CERT_ISSURE_DN VARCHAR(256) ,
	CERT_SIGNATURE BLOB ,
	CERT_ENCRYPTION BLOB 

);

-- 
CREATE TABLE TB_APP
(	
	APP_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,

	APP_NAME VARCHAR(128) NOT NULL ,
	APP_URL VARCHAR(1024) NOT NULL ,
	APP_DESC VARCHAR(1024) ,
	CHECK_STATE INTEGER DEFAULT '0' NOT NULL 

);

-- 
CREATE TABLE TB_APP_ROLE
(	
	APPROLE_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,

	APP_ID INTEGER NOT NULL ,
	APPROLE_NAME VARCHAR(128) NOT NULL ,
	APPROLE_VALUE VARCHAR(1024) NOT NULL ,
	APPROLE_DESC VARCHAR(1024) NOT NULL ,
	CHECK_STATE INTEGER DEFAULT '0' NOT NULL 

);

-- 
CREATE TABLE TB_CHECK
(	
	CHECK_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,

	ADMIN_ID INTEGER NOT NULL ,
	ACT_TIME TIMESTAMP DEFAULT 'now()' NOT NULL ,
	ACT_NAME VARCHAR(128) ,
	ACT_CLASS BLOB ,
	ACT_DESC BLOB ,
	CHECK_ADMIN_ID INTEGER ,
	CHECK_TIME TIMESTAMP ,
	CHECK_RES_ID INTEGER DEFAULT '-1' ,
	CHECK_DESC VARCHAR(2048) 

);

-- 
CREATE TABLE TB_DEPT
(	
	DEPT_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,

	DEPT_NAME VARCHAR(128) ,
	DEPT_DESC VARCHAR(512) ,
	PARENT_ID INTEGER ,
	IS_LEAF INTEGER ,
	CHECK_STATE INTEGER DEFAULT '0' 

);

-- 
CREATE TABLE TB_LOG
(	
	LOG_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,

	LOG_WHO INTEGER ,
	LOG_WHEN TIMESTAMP ,
	LOG_DO VARCHAR(128) ,
	LOG_WHAT VARCHAR(2048) ,
	LOG_RES_ID INTEGER 

);

-- 
CREATE TABLE TB_LOG_RES
(	
	LOG_RES_ID INTEGER ,
	LOG_RES VARCHAR(4) 

);

-- 
CREATE TABLE TB_ORG
(	
	ORG_ID INTEGER NOT NULL ,

	ORG_NAME VARCHAR(128) ,
	ORG_FULL_NAME VARCHAR(256) ,
	ORG_NAME_PINYIN VARCHAR(256) ,
	ORG_STATUS INTEGER ,
	ORG_INDATE TIMESTAMP ,
	ORG_UPDATE TIMESTAMP ,
	ORG_CODE VARCHAR(32) ,
	ORG_PARENT_ID INTEGER ,
	ORG_PARENT_CODE VARCHAR(64) ,
	ORG_TYPE INTEGER ,
	ORG_FULL_CODE VARCHAR(1024) ,
	ORDER_INDEX VARCHAR(32) ,
	ORDER_FULL_INDEX VARCHAR(1024) ,
	ORG_LEVEL INTEGER ,
	ORG_LINKMAN VARCHAR(32) ,
	ORG_TELEPHONE VARCHAR(20) ,
	ORG_POSTCODE VARCHAR(20) ,
	ORG_ADDRESS VARCHAR(128) ,
	ORG_DES VARCHAR(512) ,
	ADMIN_ID INTEGER 

);

-- 
CREATE TABLE TB_USER
(	
	USER_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT ,

	DEPT_ID INTEGER ,
	USER_CN VARCHAR(32) ,
	USER_NAME VARCHAR(32) ,
	USER_NAMEPY VARCHAR(32) ,
	USER_ORG VARCHAR(64) ,
	USER_UNIT VARCHAR(64) ,
	USER_OFFICE VARCHAR(128) ,
	USER_EMAIL VARCHAR(32) ,
	USER_ADDR VARCHAR(256) ,
	USER_PHONE VARCHAR(32) ,
	REG_TIME TIMESTAMP ,
	USER_RESERVE1 VARCHAR(4096) ,
	USER_RESERVE2 VARCHAR(4096) ,
	USER_RESERVE3 VARCHAR(4096) ,
	USER_RESERVE4 VARCHAR(4096) ,
	CHECK_STATE INTEGER 

);

-- 
CREATE TABLE TB_USER_RIGHTS
(	
	USER_ID INTEGER NOT NULL ,
	APP_ID INTEGER NOT NULL ,
	APPROLE_ID INTEGER 

);

